Botaniste = {}
table.insert(Botaniste,{["Abréviation"]="A. Br.",["Nom"]="Alexandre Braun",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="Adans.",["Nom"]="Adanson",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="Ait.",["Nom"]="Aiton",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="All.",["Nom"]="Allioni",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="Alph. D. C.",["Nom"]="Alphonse de Candolle",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="And.",["Nom"]="Anderson",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="Andrz.",["Nom"]="Andranz",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="Ard.",["Nom"]="Ardoino",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="Asch.",["Nom"]="Ascherson",["Lettre"]="A"})
table.insert(Botaniste,{["Abréviation"]="Babingt.",["Nom"]="Babington",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Balb.",["Nom"]="Balbis",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Barla.",["Nom"]="Barla",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bartl.",["Nom"]="Bartling",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bast.",["Nom"]="Bastard",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="C. Bauh.",["Nom"]="C. Bauhin",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="J. Bauh.",["Nom"]="J. Bauhin",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Baumg.",["Nom"]="Baumgarten",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bell.",["Nom"]="Bellardi",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bellard.",["Nom"]="Bellardi",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Benth.",["Nom"]="Bentham",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Berg.",["Nom"]="Bergeret",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bernh.",["Nom"]="Bernhardi",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bertol.",["Nom"]="Bertoloni",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bess.",["Nom"]="Besser",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bill.",["Nom"]="Billot",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bluff.",["Nom"]="Bluff",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bœnn.",["Nom"]="Von Bœnninghausen",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bœnningh.",["Nom"]="Von Bœnninghausen",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Boiss.",["Nom"]="Boissier",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Boiss. et R.",["Nom"]="Boissier et Reuter",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bonpl.",["Nom"]="Bonpland",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bord.",["Nom"]="Bordère",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bordère.",["Nom"]="Bordère",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bor.",["Nom"]="Boreau",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bornet.",["Nom"]="Bornet",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Borkh.",["Nom"]="Borkhausen",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bréb.",["Nom"]="de Brébisson",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bromf.",["Nom"]="Bromfield",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Brongn.",["Nom"]="A. Brongniart",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Brot.",["Nom"]="Brotero",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Broter.",["Nom"]="Brotero",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Bull.",["Nom"]="Bulliard",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="Burn.",["Nom"]="Burnat",["Lettre"]="B"})
table.insert(Botaniste,{["Abréviation"]="C. A. Mey.",["Nom"]="C. A. Meyer",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Camb.",["Nom"]="Cambessèdes",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Cambess.",["Nom"]="Cambessèdes",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Campd.",["Nom"]="Campdera",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Cass.",["Nom"]="Cassini",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Cav.",["Nom"]="Cavanilles",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Chabert.",["Nom"]="Chabert",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Cham.",["Nom"]="de Chamisso",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Chaix.",["Nom"]="Chaix",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Chaub.",["Nom"]="Chaubard",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Choisy.",["Nom"]="Choisy",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Clairv.",["Nom"]="Clairville",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Clav.",["Nom"]="Clavaud",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Clus.",["Nom"]="Clusius (L'Écluse)",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Cornuti.",["Nom"]="Cornuti",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Coss.",["Nom"]="E. Cosson",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Coss. et Germ.",["Nom"]="Cosson et Germain de Saint-Pierre",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Coult.",["Nom"]="T. Coulter",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Crantz.",["Nom"]="Crantz",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Curt.",["Nom"]="Curtis",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Cyr.",["Nom"]="Cyrillo",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Cyril.",["Nom"]="Cyrillo",["Lettre"]="C"})
table.insert(Botaniste,{["Abréviation"]="Dalib.",["Nom"]="Dalibard",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dcne.",["Nom"]="Decaisne",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="DC.",["Nom"]="A. Pyr. de Candolle",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Delarb.",["Nom"]="Delarbre",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Delast.",["Nom"]="Delastre",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Del.",["Nom"]="Delile",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Desf.",["Nom"]="Desfontaines",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Deség.",["Nom"]="Deséglise",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Desp.",["Nom"]="Desportes",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Desr.",["Nom"]="Desrousseau",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Desv.",["Nom"]="Desvaux",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dietr.",["Nom"]="Dietrich",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dill.",["Nom"]="Dillenius",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Don.",["Nom"]="Don",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dub.",["Nom"]="Duby",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Duch.",["Nom"]="Duchesne",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Duf.",["Nom"]="L. Dufour",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dufr.",["Nom"]="Dufresne",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dumort.",["Nom"]="Dumortier",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dun.",["Nom"]="Dunal.",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dupuy.",["Nom"]="Dupuy",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Dur.",["Nom"]="Durieu de Maisonneuve",["Lettre"]="D"})
table.insert(Botaniste,{["Abréviation"]="Ehrh.",["Nom"]="Ehrhart",["Lettre"]="E"})
table.insert(Botaniste,{["Abréviation"]="Endl.",["Nom"]="Endlicher",["Lettre"]="E"})
table.insert(Botaniste,{["Abréviation"]="Engelm.",["Nom"]="Engelmann",["Lettre"]="E"})
table.insert(Botaniste,{["Abréviation"]="Fabre.",["Nom"]="Fabre",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Fenzl.",["Nom"]="Fenzl",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Fing.",["Nom"]="Fingerhuth",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Fisch.",["Nom"]="Fischer",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Fleury.",["Nom"]="Fleury",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Forst.",["Nom"]="Forster",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Frank.",["Nom"]="Frankenius",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Fres.",["Nom"]="Fresenius",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Fries.",["Nom"]="Fries",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Fuschs.",["Nom"]="Fuschius",["Lettre"]="F"})
table.insert(Botaniste,{["Abréviation"]="Gærn.",["Nom"]="Gærtner",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Gant.",["Nom"]="Gantener",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Garke.",["Nom"]="Garke",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Gaud.",["Nom"]="Gaudin",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Gay.",["Nom"]="J. Gay",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="G. G.",["Nom"]="Grenier et Godron",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Gmel.",["Nom"]="Gmelin",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Godr.",["Nom"]="Godron",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Good.",["Nom"]="Goodenough",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Gouan.",["Nom"]="Gouan",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Greml.",["Nom"]="Gremli",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Gren.",["Nom"]="Grenier",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Griseb.",["Nom"]="Grisebach",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Guép.",["Nom"]="Guépin",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Guers.",["Nom"]="Guersant",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Guett.",["Nom"]="Guettard",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Guss.",["Nom"]="Gussone",["Lettre"]="G"})
table.insert(Botaniste,{["Abréviation"]="Hack.",["Nom"]="Hackel",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hall.",["Nom"]="Haller",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hartm.",["Nom"]="Hartmann",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Haw.",["Nom"]="Haworth",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hayne.",["Nom"]="Hayne",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Herm.",["Nom"]="Hermann",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hoffm.",["Nom"]="Hoffmann",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hoffms.",["Nom"]="Hoffmannsegg",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hook.",["Nom"]="Hooker",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hopp., Hoppe.",["Nom"]="Hoppe",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Horn.",["Nom"]="Hornemann",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Host.",["Nom"]="Host",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Huds.",["Nom"]="Hudson",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Huet.",["Nom"]="Huet",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Hummicki.",["Nom"]="Hummicki",["Lettre"]="H"})
table.insert(Botaniste,{["Abréviation"]="Jacq.",["Nom"]="Jacquin",["Lettre"]="J"})
table.insert(Botaniste,{["Abréviation"]="Jan.",["Nom"]="Jan",["Lettre"]="J"})
table.insert(Botaniste,{["Abréviation"]="Jaub.",["Nom"]="Comte Jaubert",["Lettre"]="J"})
table.insert(Botaniste,{["Abréviation"]="Jord.",["Nom"]="Jordan",["Lettre"]="J"})
table.insert(Botaniste,{["Abréviation"]="Juss.",["Nom"]="A. Laurent de Jussieu",["Lettre"]="J"})
table.insert(Botaniste,{["Abréviation"]="Kern.",["Nom"]="Kerner",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kirschleg.",["Nom"]="Kirschleger",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kit.",["Nom"]="Kitaibel",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Koch.",["Nom"]="Koch",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kœl.",["Nom"]="Kœler",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kœn.",["Nom"]="Kœnig",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kral.",["Nom"]="Kralik",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Krock.",["Nom"]="Krocker",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kœrnck.",["Nom"]="Kœrnicke",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kunth.",["Nom"]="Kunth",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Kütz.",["Nom"]="Kützing",["Lettre"]="K"})
table.insert(Botaniste,{["Abréviation"]="Lag., Lagas.",["Nom"]="Lagasca",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lab.",["Nom"]="Labarpe",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lam.",["Nom"]="Lamark",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lamt.",["Nom"]="Lamotte",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lange.",["Nom"]="Lange",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lap.",["Nom"]="P. de la Peyrouse",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lat.",["Nom"]="Latourette",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lec.",["Nom"]="Lecoq",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lec. et Lmt.",["Nom"]="Lecoq et Lamotte",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Ledeb.",["Nom"]="Ledebourg",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Leers.",["Nom"]="Leers",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lefèvre.",["Nom"]="Lefèvre",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Le Gall.",["Nom"]="Le Gall",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lehm.",["Nom"]="Lehmann",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lej.",["Nom"]="Lejeune",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Leonh.",["Nom"]="Leonhardi",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Less.",["Nom"]="Lessing",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lestib.",["Nom"]="Lestiboudois",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Leyss.",["Nom"]="Leysser",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="L'Hérit.",["Nom"]="L'Héritier",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lighf.",["Nom"]="Lightfoot",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lindl.",["Nom"]="Lindley",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Link.",["Nom"]="Link",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Link et Hoffm.",["Nom"]="Link et Hoffmann",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="L.",["Nom"]="Linné",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lloyd.",["Nom"]="Lloyd",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lob.",["Nom"]="Lobel",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lois.",["Nom"]="Loiseleur Deslonchamps",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Loret.",["Nom"]="Loret",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Lor. et B.",["Nom"]="Loret et Barrandon",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Loudon.",["Nom"]="Loudon",["Lettre"]="L"})
table.insert(Botaniste,{["Abréviation"]="Mab.",["Nom"]="Mabille",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="M. B.",["Nom"]="Marschail von Bieberstein",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Marcilly.",["Nom"]="Marcilly",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mart.",["Nom"]="Martius",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mauri.",["Nom"]="Mauri",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Meisn.",["Nom"]="Meisner",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="M. et K.",["Nom"]="Mertens et Koche",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mér.",["Nom"]="Mérat",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mert.",["Nom"]="Mertens",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mey.",["Nom"]="Meyer",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Michal.",["Nom"]="Michalet",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Michx.",["Nom"]="Michaux",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mich.",["Nom"]="Micheli",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mill.",["Nom"]="Miller",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mirb.",["Nom"]="Mirbet",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mœnch.",["Nom"]="Mœnch",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Moq.",["Nom"]="Moquin-Tandon",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Moretti.",["Nom"]="Moretti",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Moris.",["Nom"]="Morison",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mull.",["Nom"]="Muller",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Murith.",["Nom"]="Murith",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Murr.",["Nom"]="Murray",["Lettre"]="M"})
table.insert(Botaniste,{["Abréviation"]="Mut.",["Nom"]="Mutel",["Lettre"]="M"})
